version: "3.9"

services:
  nextcloud:
    image: nextcloud:27.1.4-fpm
    restart: unless-stopped
    volumes:
      - ./_data:/var/www/html
    ports:
      - 30000:80
    environment:
      POSTGRES_HOST: www.buddhiko.com
      POSTGRES_DB: nextcloud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/passwd
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/passwd
      PHP_UPLOAD_LIMIT: 2G
    secrets:
      - passwd

secrets:
  passwd:
    file: ../_secrets/passwd.txt
