version: "3.9"

services:
  nextcloud:
    image: nextcloud:27.1.4-apache
    container_name: nextcloud
    volumes:
      - ./_data:/var/www/html
    ports:
      - 30000:80
    environment:
      OVERWRITEPROTOCOL: https
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.buddhiko.com
      PHP_UPLOAD_LIMIT: 2G
    restart: unless-stopped
