version: "3.9"

services:
  caddy:
    image: caddy:2.7-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./_files:/srv
      - ./_data/data:/data
      - ./_data/config:/config
    restart: unless-stopped
