version: "3.9"

services:
  caddy:
    image: caddy:2.7-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DIRECTUS_IP=${DIRECTUS_IP}
    env_file:
      - ../.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./_site:/srv
      - ./_data/data:/data
      - ./_data/config:/config
    restart: unless-stopped
