version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: pali
      POSTGRES_PASSWORD_FILE: /run/secrets/passwd.txt
    networks:
      - directus
    volumes:
      - /run/secrets:/run/secrets
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # cache:
  #   image: redis
  #   container_name: cache
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - directus

  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - 9000:9000
    volumes:
      - /home/shun/pali-cms/pali/config.js:/directus/config.js # must absolutely path
      - /run/secrets:/run/secrets
      - directus_uploads:/directus/uploads
      - directus_db:/directus/database
    networks:
      - directus
    depends_on:
      # - cache
      - postgres
    environment:
      CONFIG_PATH: /directus/config.js
    restart: unless-stopped

networks:
  directus:

volumes:
  postgres_data:
  directus_db:
  directus_uploads:
