version: "3.9"

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: pali
      POSTGRES_PASSWORD_FILE: /run/secrets/passwd
    secrets:
      - passwd
    volumes:
      - ./_data/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # cache:
  #   image: redis
  #   container_name: cache
  #   ports:
  #     - 6379:6379

  directus:
    image: directus/directus:10.7
    container_name: directus
    ports:
      - 9000:9000
    volumes:
      - ./config.json:/directus/config.json
      - ../_files/uploads:/directus/uploads
      - ./_data/directus_db:/directus/database
    depends_on:
      # - cache
      - postgres
    environment:
      CONFIG_PATH: /directus/config.json
    secrets:
      - email
      - passwd
    restart: unless-stopped

secrets:
  passwd:
    file: ../_secrets/passwd.txt
  email:
    file: ../_secrets/email.txt
