version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 10000:9443
    volumes:
      - ./_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
